openapi: 3.1.0
info:
  title: EasyData v16.7.9 – Fortress API
  description: >
    Authoritative, governed OpenAPI contract for EasyData v16.7.x.
    NDJSON-only streaming. Confidence-tiered execution.
    Exploration may suggest. Governance alone may execute.
  version: 16.7.9
  contact:
    name: EasyData Architecture Board
  license:
    name: Proprietary

servers:
  - url: /api/v1

security:
  - BearerAuth: []

tags:
  - name: Ask
  - name: Training
  - name: Assets
  - name: Scheduling
  - name: Admin
  - name: Sandbox

paths:

  /ask:
    post:
      tags: [Ask]
      summary: Execute governed analytical query (NDJSON stream)
      operationId: askQuestion
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AskRequest'
      responses:
        '200':
          description: NDJSON stream
          content:
            application/x-ndjson:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/ThinkingChunk'
                  - $ref: '#/components/schemas/TechnicalViewChunk'
                  - $ref: '#/components/schemas/DataChunk'
                  - $ref: '#/components/schemas/BusinessViewChunk'
                  - $ref: '#/components/schemas/EndChunk'
                  - $ref: '#/components/schemas/ErrorChunk'

  /train/v1/schema:
    post:
      tags: [Training]
      summary: Upload schema metadata
      operationId: trainSchema
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrainingItemRequest'
      responses:
        '201':
          description: Created

  /train/v1/ddl:
    post:
      tags: [Training]
      summary: Upload DDL statements
      operationId: trainDDL
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrainingItemRequest'
      responses:
        '201':
          description: Created

  /train/v1/documentation:
    post:
      tags: [Training]
      summary: Upload business documentation
      operationId: trainDocumentation
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrainingItemRequest'
      responses:
        '201':
          description: Created

  /train/v1/sql:
    post:
      tags: [Training]
      summary: Upload curated question-SQL pairs
      operationId: trainSQLPairs
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrainingItemRequest'
      responses:
        '201':
          description: Created

  /train/v1/csv:
    post:
      tags: [Training]
      summary: Upload reference CSV data
      operationId: trainCSV
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrainingItemRequest'
      responses:
        '201':
          description: Created

  /train/v1/assumptions:
    get:
      tags: [Training]
      summary: List detected assumptions
      operationId: listAssumptions
      security:
        - BearerAuth: []
      responses:
        '200':
          description: OK

  /train/v1/assumptions/{id}/approve:
    post:
      tags: [Training]
      summary: Approve assumption
      operationId: approveAssumption
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: string, format: uuid }
      responses:
        '200':
          description: Approved

  /train/v1/assumptions/{id}/reject:
    post:
      tags: [Training]
      summary: Reject assumption
      operationId: rejectAssumption
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: string, format: uuid }
      responses:
        '200':
          description: Rejected

  /platform/v1/assets/queries:
    post:
      tags: [Assets]
      summary: Create QueryAsset
      operationId: createQueryAsset
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryAssetCreate'
      responses:
        '201':
          description: Created

    get:
      tags: [Assets]
      summary: List QueryAssets
      operationId: listQueryAssets
      security:
        - BearerAuth: []
      responses:
        '200':
          description: OK

  /platform/v1/assets/queries/{id}/share:
    post:
      tags: [Assets]
      summary: Share QueryAsset
      operationId: shareQueryAsset
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: string, format: uuid }
      responses:
        '200':
          description: Shared

  /platform/v1/assets/queries/{id}:
    delete:
      tags: [Assets]
      summary: Archive QueryAsset
      operationId: archiveQueryAsset
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: string, format: uuid }
      responses:
        '204':
          description: Archived

  /platform/v1/schedules:
    post:
      tags: [Scheduling]
      summary: Create schedule for approved asset
      operationId: createSchedule
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScheduleCreate'
      responses:
        '201':
          description: Created

  /admin/v1/audit/logs:
    get:
      tags: [Admin]
      summary: Read audit logs
      operationId: getAuditLogs
      security:
        - BearerAuth: []
      responses:
        '200':
          description: OK

  /admin/v1/schema/drift:
    get:
      tags: [Admin]
      summary: List schema drift events
      operationId: listSchemaDrifts
      security:
        - BearerAuth: []
      responses:
        '200':
          description: OK

  /admin/v1/toggles:
    post:
      tags: [Admin]
      summary: Toggle feature flags
      operationId: toggleFeature
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FeatureToggle'
      responses:
        '200':
          description: Updated

  /admin/sandbox/promote:
    post:
      tags: [Sandbox]
      summary: Promote sandbox discovery item
      operationId: promoteSandboxItem
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SandboxPromotion'
      responses:
        '200':
          description: Promoted

components:

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:

    AskRequest:
      type: object
      required: [question, stream]
      properties:
        question:
          type: string
        stream:
          type: boolean
        context:
          type: object
          additionalProperties: true

    BaseChunk:
      type: object
      required: [type, trace_id, confidence_tier, timestamp]
      properties:
        type:
          type: string
        trace_id:
          type: string
          format: uuid
        confidence_tier:
          type: string
          enum: [TIER_0_FORTRESS, TIER_1_LAB]
        timestamp:
          type: string
          format: date-time

    ThinkingChunk:
      allOf:
        - $ref: '#/components/schemas/BaseChunk'
        - type: object
          properties:
            type:
              enum: [thinking]
            status:
              type: string

    TechnicalViewChunk:
      allOf:
        - $ref: '#/components/schemas/BaseChunk'
        - type: object
          properties:
            type:
              enum: [technical_view]
            sql:
              type: string
            assumptions:
              type: array
              items: { type: string }
            policy_hash:
              type: string

    DataChunk:
      allOf:
        - $ref: '#/components/schemas/BaseChunk'
        - type: object
          properties:
            type:
              enum: [data_chunk]
            columns:
              type: array
              items: { type: string }
            rows:
              type: array
              items:
                type: array
                items: {}
            row_count:
              type: integer

    BusinessViewChunk:
      allOf:
        - $ref: '#/components/schemas/BaseChunk'
        - type: object
          properties:
            type:
              enum: [business_view]
            summary:
              type: string
            chart_config:
              type: object
              additionalProperties: true

    EndChunk:
      allOf:
        - $ref: '#/components/schemas/BaseChunk'
        - type: object
          properties:
            type:
              enum: [end]
            duration_ms:
              type: integer

    ErrorChunk:
      allOf:
        - $ref: '#/components/schemas/BaseChunk'
        - type: object
          properties:
            type:
              enum: [error]
            error_code:
              type: string
            message:
              type: string

    TrainingItemRequest:
      type: object
      required: [content]
      properties:
        content:
          type: string
        metadata:
          type: object
          additionalProperties: true

    QueryAssetCreate:
      type: object
      required: [trace_id, title]
      properties:
        trace_id:
          type: string
          format: uuid
        title:
          type: string
        visibility:
          type: string
          enum: [private, shared]

    ScheduleCreate:
      type: object
      required: [asset_id, cron]
      properties:
        asset_id:
          type: string
          format: uuid
        cron:
          type: string
        delivery:
          type: array
          items:
            type: string
            enum: [email, dashboard]

    FeatureToggle:
      type: object
      required: [feature, enabled, reason]
      properties:
        feature:
          type: string
        enabled:
          type: boolean
        reason:
          type: string

    SandboxPromotion:
      type: object
      required: [discovery_id, reason]
      properties:
        discovery_id:
          type: string
          format: uuid
        reason:
          type: string
