openapi: 3.1.0

info:
  title: EasyData Fortress Backend API
  version: 16.7.9
  description: |
    Production-grade OpenAPI specification for EasyData Fortress v16.7.9.

    Enforces:
    - Schema Scope Wizard
    - Controlled Knowledge Population (Stage 6)
    - Permission-based RBAC
    - Auditable & reversible training
    - Policy-bound SQL and RAG execution
    - Stable NDJSON / SSE streaming contracts

servers:
  - url: /api/v1

security:
  - bearerAuth: []

paths:
  $ref: ./paths.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    $ref: ./schemas.yaml
